[phases.setup]
nixPkgs = ["nodejs_22_12", "python311"]
cmds = ["npm ci","npm run setup:python"]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npx prisma generate && npx prisma migrate deploy && npm run start"
