[phases.setup]
nixPkgs = ["nodejs_22", "python311", "pip", "bash"]
cmds = ["npm ci"]

[phases.python]
commands = [
  "cd model_api && python3 -m venv venv",
  "cd model_api && ./venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npx prisma generate && npx prisma migrate deploy && npm run start"
