[phases.setup]
nixpkgsArchive = '51ad838b03a05b1de6f9f2a0fffecee64a9788ee'
nixPkgs = ["nodejs_22", "python311"]
cmds = ["npm ci --omit=dev","npm run setup:python"]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npx prisma generate && npx prisma migrate deploy && npm run start"
