// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type ReadRootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type ReadRootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReadItemItemsItemIdGetData = {
  body?: never;
  path: {
    /**
     * Item Id
     */
    item_id: number;
  };
  query?: {
    /**
     * Q
     */
    q?: string;
  };
  url: "/items/{item_id}";
};

export type ReadItemItemsItemIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadItemItemsItemIdGetError =
  ReadItemItemsItemIdGetErrors[keyof ReadItemItemsItemIdGetErrors];

export type ReadItemItemsItemIdGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
